project:
  type: website
  output-dir: docs 

website:
  title: "quarto_web"
  navbar:
    left:
      - href: DataVisualization.ipynb
        text: Renewable Energy Consumption Analysis

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    embed-resources: true

execute: 
  echo: true



